[package]
name = "peppi"
version = "0.1.0"
authors = ["melkor <hohav@fastmail.com>"]
edition = "2018"

[dependencies]
byteorder = "1"
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "2.33", optional = true }
encoding_rs = "0.8"
hdf5 = { version = "0.7", optional = true }
jmespatch = { version = "0.3", features = ["specialized"], optional = true }
log = "0.4"
mimalloc = { version = "0.1", default-features = false, optional = true }
num_enum = "0.5"
num-traits = "0.2"
pretty_env_logger = { version = "0.4", optional = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", optional = true }

[lib]
name = "peppi"
path = "src/lib.rs"

[features]
build-binary = ["clap", "jmespatch", "mimalloc", "pretty_env_logger", "serde_json"]

[profile.release]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
lto = true
codegen-units = 1
panic = "abort"
incremental = false
rpath = false

[[bin]]
name = "slp"
path = "src/bin.rs"
required-features = ["build-binary"]
