[package]
name = "peppi"
version = "0.1.0"
authors = ["melkor <hohav@fastmail.com>"]
edition = "2018"

[dependencies]
byteorder = "1"
chrono = { version = "0.4", features = ["serde"] }
encoding_rs = "0.8"
hdf5 = { version = "0.7", optional = true }
log = "0.4"
num_enum = "0.5"
num-traits = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[lib]
name = "peppi"
path = "src/lib.rs"
