[package]
name = "peppi"
version = "0.1.0"
authors = ["melkor <hohav@fastmail.com>"]
edition = "2018"

[dependencies]
byteorder = "1"
chrono = { version = "0.4", features = ["serde"] }
clap = "2.33"
encoding_rs = "0.8"
jmespatch = { version = "0.3.0", features = ["specialized"] }
log = "0.4"
mimalloc = { version = "0.1.22", default-features = false }
num_enum = "0.4"
pretty_env_logger = "0.4"
regex = "1.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[lib]
name = "peppi"
path = "src/lib.rs"

[profile.release]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
lto = true
codegen-units = 1
panic = "abort"
incremental = false
rpath = false

[[bin]]
name = "slp"
path = "src/bin.rs"
